[14.0][IMP] Combo category behavior
kmee/pos pull request #23
Opened 2023-01-05 18:02 UTC by ygcarvalh

Implementation of an improvement aimed at adding a field that defines different behaviors for a category of a combo. At this first moment, it is possible that the category duplicates the items or that it has control of the quantity to be added for each item.

2023-01-06 11:58 UTC, luismalta requested changes
@ygcarvalh Depois consegue subir uma instância no gitlab mudando o repo / branch do combo para essa sua? Assim conseguimos testar funcionalmente também.

2023-01-06 11:58 UTC, luismalta commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                this.selectedOrderline.set_quantity(1);
Acho melhor já deixar a quantidade e o preço da linha do produto original já vir correto da função _mount_products_to_add_map. Porque assim não será preciso mexer em uma linha que já foi adicionada a conta.

2023-01-06 11:58 UTC, luismalta commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                }
Como os dados dos produtos devem ser iguais para todas as duplicatas, acho melhor adicionar só uma linha com a quantidade de duplicatas correspondente. Dessa forma tira a complexidade de mais um for no algorítimo.

2023-01-06 11:58 UTC, luismalta commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                        }
Será que não conseguimos estender essa lógica do rollback para a adição de todos os produtos no combo?

2023-01-09 10:51 UTC, ygcarvalh commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                        }
Não entendi sua dúvida, pode explicar? Porque até onde eu testei, é exatamente esse o comportamento que vai ser realizado por essa função do rollback.

2023-01-09 13:29 UTC, luismalta commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                        }
Pelo que vi, hoje o try só cobre a adição de linhas duplicadas. A ideia seria ele cobrir também a inserção de qualquer item do combo (linha 79). Dessa forma, caso aconteça algum problema nesses casos, ele também executará o rollback.

2023-01-09 13:36 UTC, ygcarvalh commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                        }
Ah, sim. Mas na linha 80 eu faço o mesmo processo que é feito nas linhas duplicadas: eu adiciono ele para o array.

2023-01-09 13:48 UTC, luismalta commented on pos_product_template_combo/static/src/js/ProductScreen.js
> +                        }
Mas se der problema na adição de um item normal do combo, como essa parte do código não está no try catch, ele não executará a função do rollback.

2023-01-09 14:42 UTC, ygcarvalh commented
@luismalta pode revisar de novo, por favor?

2023-01-09 16:45 UTC, luismalta approved these changes
LGTM. Só esperar o pipeline do Gitlab voltar a funcionar para fazer o teste funcional.

2023-01-11 20:14 UTC, merged